name: Docs2Pages
on:
  push:
    branches: [ "main" ]
#  push:
#    tags: '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: |
           **/pyproject.toml
           **/requirements*.txt
    - uses: abatilo/actions-poetry@v2.1.3
    - name: install
      run: (cd src && poetry install -E docs)
    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        poetry run sphinx-build -b html . _build
        cp -r _build/* ../gh-pages/
#    - name: Deploy documentation
#      if: ${{ github.event_name == 'push' }}
#      uses: JamesIves/github-pages-deploy-action@4.1.4
#      with:
#        branch: gh-pages
#        folder: gh-pages
